### ISSUE TITLE
put secrets in separate files

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/SATOSA#167]
Config data and secrets (such as proxy_conf/STATE_ENCRYPTION_KEY) should go into separate files. Rationale: Deployment environments (e.g. Openshift)  pull the configuration from some external repository but inject secrets locally.

**Comment by leifj** [comment]
On 2017-11-06 10:45, Rainer Hörbe wrote:
> Config data and secrets (such as proxy_conf/STATE_ENCRYPTION_KEY) should
> go into separate files. Rationale: Deployment environments (e.g.
> Openshift) pull the configuration from some external repository but
> inject secrets locally.

They can already be overriden by environment variables. Isn't that good
enough?

**Comment by rhoerbe** [comment]
Env variables are usually not good enough, because they are visible to everybody in the same process namespace. So for better segregation files are preferred.

**Comment by c00kiemon5ter** [comment]
Files are also accessible to everything in the same process namespace. Security is built around users and groups that query the filesystem (process owners – (e)uid and (e)gid). The same principles apply once the data is given to the process. Not trusting the device that a process is running on, hides other assumptions that should be treated in another context. Serious security separates applications and secrets by risk analysis results.

I would note that environment variables are not displayed by the process listing tools (ps, (h)top, etc) unless the process is owned by the user that initiated the query, whereas command line arguments are visible to all users. 

I generally feel that the current handling is fine, but I can see the initiative for improvement. I would argue that for usability reasons (_principle of least astonishment_), the common hierarchy of argument-handling should be followed: 

- static configuration
- environment variables
- command line option

where each is overridden by the next one.

With such a mechanism in place, both the existing scenario and the one requested by @rhoerbe can be supported.

**Comment by c00kiemon5ter** [comment]
I'm coming back to this after some time, as I have been looking into pysaml2's and satosa's configurations. There two separate things discussed here:

1. whether configuration files are more secure than environment variables
2. whether configuration options regarding secrets should be split to a separate configuration unit

On the outset, both methods (configuration files and environment variables) seem equal in flexibility and thus security considerations. However, there are differences (a) historically and (b) on the flexibility at runtime.

- Whether one points an app to a different configuration file, or change the environment variables before starting the app, both ways are equally flexible.
- Environment variables usually have `key=value` form. The same can be done with configuration files. Files tend to adopt a certain filetype (yaml, json, ini, etc). This restricts the usage to tools that can parse those formats; while key-value are universally understood. Environmental variable promote the usage of the key-value form.
- Configuration files are also easier to become part of the distribution, thus easier to end up in repositories by mistake, exposing app-secrets that should not be public. Other issues would be, backing up a system(!) - should files with secrets be part of a backup? The same thing can happen with environment variables, as people tend to _create files_ (`.env`, `environ`, etc) and source them before executing the app; but this is against the usage of environment variables. The respective downside with environment variables is that if the app crashes the information included may include the environment and thus leak the configuration secrets*¹ (more on this later).
- Access to the configuration file is restricted by the file permissions (not taking into account finer grain systems like SELinux). The owning user and root has full permissions over what operations are allowed to the file. The same way, environment variables are private and can only be seen by the user*² that invoked the app and root.

> *²This was not always the case. Historically, environment variables were public; as unix passwords were in plain text before `/etc/shadow` was invented. This was long ago and this should only apply to legacy systems.

Configuration should be strictly separated from code. Configuration options should be granular controls, fully orthogonal to each other. The configuration is the set of constrains that form the particular environment that the app will run within. Thus, conceptually, the environment is the right place to store the configuration.

In bigger installations, the configuration is a separate service that provides the requested values to other services or apps. These tools scale from [in kernel keyrings][kk], [local userspace keymanagers][km] up to [discovery-services][ds] or [secrets-management][sm] [with high grained ACLs][ob].

  [kk]: https://www.kernel.org/doc/Documentation/security/keys.txt
  [km]: https://pypi.org/project/keyring/
  [ds]: https://github.com/coreos/etcd
  [sm]: https://www.vaultproject.io/
  [ob]: https://wiki.openstack.org/wiki/Barbican

But, the point remains - the configuration should not be coupled with code, it should be defined by the environment that the app will run within. The environment changes; it can be the development cluster, the QA or staging step, the deployment, the developer's local setup, and so on - the code stays the same.

In smaller installations the tools that define this environment are configuration management tools like ansible, chef, puppet, etc, and nowadays containerization (mainly docker). While, the configuration management tools are built to manage configuration _files_, containerization works by defining the dependencies needed for an app to run, and part of the dependencies is the configuration usually defined by environment variables (see docker-compose `environment:`, kubernetes `env:`, etc.)

Ultimately, any options we need will have some mode of access - they need to live somewhere and will need to be accessed as plain text. (Very interesting concept by `openstack/barbican` that [they separated the value that was stored from its representation][yt]; one could ask a option/secret as a file or text value etc.) What we should make sure is that this access window is as small as possible.

  [yt]: https://www.youtube.com/watch?v=BY4iVTbGk30#t=23m38s

Where things differ is at the runtime. At the runtime a file will be available to any process running under the same user. Forked processes will also have access. Environment variables are not readily available to another process running under the same user, but they can be looked up. Forked processes also inherit their parents environment - but any app written with security in mind must sanitise the environment before spawning another process (see and use `man execve`).

This last sentence hides something very important. Configuration files are static and thus a program cannot partition access to the file contents - filesystem permissions apply on the whole file. The only way to do that, is by deleting the file. The environment on the other hand, once the application is started is under the application's control. The app can read an option/secret from the environment and then -immediately after consumption/minimizing the access window- delete that environment variable (*¹ thus also preventing leakage on a potential crash.) This makes a big difference, imho.

At this point, I think environment variables can provide better security, if the app sanitises the environment as needed.

---

Regarding splitting the configuration to multiple files where one groups all the secrets, I think this does not make things any better; I would argue it makes things more fragile when one needs to control/manage multiple files. All tools that provide configuration management allow one to store secrets as variables and use them in configuration templates. There is no need for us to do that and instead we should be using those tools.

**Comment by c00kiemon5ter** [comment]
@skanct made a remark on how should a service gracefully reload to pick up a new configuration when the configuration is stored in environment variables.

The answer is _it doesn't_. The app is configured when it starts. The app never restarts; it is only started and stopped. The app itself, does not handle connections, this is done by the webserver (for python that usually means `gunicorn`.) The app is only invoked to perform a task in reaction to a request. The webserver is responsible to gracefully close the connections after they have been served.

`gunicorn` [does that][gsh]; it can gracefully exit or restart (or do other things) by interpreting the _signals_ it receives. If we want to gracefully stop an instance running with `gunicorn` we send `SIGTERM`, if we want to restart an instance we send `SIGHUP`. By sending the appropriate signal, `gunicorn` will first serve any connections that are queued and then stop or restart.

This is different though, to having no downtime. `gunicorn` takes some time to restart, the app takes some time to load, and while this is happening no connections can be served. There is nothing we can about that; things take time to initialize and we cannot manipulate time.

The only way to avoid downtime is by having multiple instances running in parallel. When one instance is upgrading, the others continue to serve as normal. This creates a _transition period_ where by the end of it, all (or _some_ depending on the upgrade strategy) instances should be upgraded. This requires that the instances are hidden behind a common entry point. This is usually achieved by load balancing.

A load balancer (typically `nginx` or `haproxy`) can advertise a singe entry point (a set of IP addresses) while internally it distributes the requests to multiple backends (multiple instances running the app). The way the distribution happens is configurable to meet the app's requirements. For the load balancer to work smoothly there are two requirements: the load balancer needs to know the backends and the load balancer needs to know which backends are ready to serve. Discovery is done by means of configuration and availability is checked by invoking [health checks][nhc], usually handled by the load balancer itself for free.

How does this all work together?
The load balancer acts as a single entry point, it accepts connections and forwards requests by a specified strategy to backend servers. The backend server handles a request, runs the app, and creates a response.
When app needs to upgrade, instances are upgraded in a rolling fashion. Each instance in turn is taken down and the load balancer stops relaying requests to that backend. The instance upgrades, becomes available again, and the load balancer adds it back to the available backends. At the end all backends are running upgraded instances. While the upgrade was taking place, the non-upgraded and the already-upgraded backends continue serving as normal.
The whole process may be tedious, and that's why it is automated with tools called orchestrators. Orchestrators make the above process (and other such processes) easy, as they automate the time and constrains in which it takes place - iow, they define the _upgrade strategy_. To make this possible, orchestrators are tied to a specific technology stack, ie. `kubernetes` supports `docker` (not every container format out there.)

The above is in line with the idea of _immutable infrastructure_. Each running service runs from a clean state. There is no upgrade that can leave old configuration values or drift from the configuration state that it started from. This makes troubleshooting easier and possibly reproducible.


  [gsh]: http://docs.gunicorn.org/en/stable/signals.html
  [nhc]: https://nginx.org/en/docs/http/load_balancing.html#nginx_load_balancing_health_checks

**Comment by rhoerbe** [comment]
That approach is very useful indeed. It applies to re-configuration, upgrades, metadata reload and A/B-testing.

For the record: My remark from Nov 6 that env-variables are not good enough to hold secrets was invalid (see mailing list).

**Comment by c00kiemon5ter** [comment]
I am closing this for now. I will be reworking both the SATOSA and pysaml2 configuration handling.
