### ISSUE TITLE
Docker image lacks ldap3

### ISSUE THREAD

**Issue by steff-o** [IdentityPython/SATOSA#276]
The linked docker image does not contain all dependencies for the ldap attributes microservice. This may or may not be intentional, but it makes the image not turnkey if using the ldap attributes microservice plugin.

**Comment by c00kiemon5ter** [comment]
We are going to be splitting the micro-services out, each to its own repo, so that dependencies for micro-services are separate form the core. Until this is done, the core has to include anything that maybe needed; which is not very flexible.

Now, `ldap3` is actually [listed as a dependency](https://github.com/IdentityPython/SATOSA/blob/c3d9c64/setup.py#L28-L30), but it is part of the "extra requires". Docker is using the [`docker/setup.sh` file](https://github.com/IdentityPython/SATOSA/blob/master/docker/setup.sh#L7) to install satosa, and it does so by

```bash
pip install /src/satosa/
```

which might be better to change to

```python
pip install -e /src/satosa/[ldap]
```

or extend the dockerfile to accommodate for more options pased by the system.
