### ISSUE TITLE
satosa-saml-metadata in docker image is broken?

### ISSUE THREAD

**Issue by advgal** [IdentityPython/SATOSA#310]
## Code Version

https://hub.docker.com/u/satosa/
"Id": "sha256:a7db6d314b3116f8ae64f291e4096e912807893fd2d84e6b8d49c98d8324e83d"
"Created": "2019-11-07T15:29:06.6296864Z"

## Expected Behavior

satosa-saml-metadata should display a help message

## Current Behavior

satosa-saml-metadata fails with an error:

% docker run -it satosa/satosa /opt/satosa/bin/satosa-saml-metadata --help
Traceback (most recent call last):
  File "/opt/satosa/bin/satosa-saml-metadata", line 5, in <module>
    from satosa.scripts.satosa_saml_metadata import construct_saml_metadata
  File "/opt/satosa/lib/python3.5/site-packages/satosa/scripts/satosa_saml_metadata.py", line 7, in <module>
    from ..metadata_creation.saml_metadata import create_entity_descriptors
  File "/opt/satosa/lib/python3.5/site-packages/satosa/metadata_creation/saml_metadata.py", line 10, in <module>
    from ..backends.saml2 import SAMLBackend
  File "/opt/satosa/lib/python3.5/site-packages/satosa/backends/saml2.py", line 21, in <module>
    from satosa.base import SAMLBaseModule
  File "/opt/satosa/lib/python3.5/site-packages/satosa/base.py", line 12, in <module>
    from satosa.micro_services import consent
  File "/opt/satosa/lib/python3.5/site-packages/satosa/micro_services/consent.py", line 15, in <module>
    from satosa.internal import InternalData
  File "/opt/satosa/lib/python3.5/site-packages/satosa/internal.py", line 132
    **kwargs,
            ^
SyntaxError: invalid syntax

## Steps to Reproduce

% docker run -it satosa/satosa /opt/satosa/bin/satosa-saml-metadata --help

**Comment by c00kiemon5ter** [comment]
Yes, it seems it is broken because we did not update the python version
that is used. The latest satosa expects python 3.6 or newer.

**Comment by advgal** [comment]
It seems that it is still broken:

% docker run satosa/satosa /opt/satosa/bin/satosa-saml-metadata --help
Traceback (most recent call last):
  File "/opt/satosa/bin/satosa-saml-metadata", line 8, in <module>
    sys.exit(construct_saml_metadata())
  File "/opt/satosa/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/satosa/lib/python3.6/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/opt/satosa/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

**Comment by advgal** [comment]
Yes it works, I tested it already.

**Comment by c00kiemon5ter** [comment]
> I'm not sure if we should put the locale option in the Dockerfile

It should be configured by the user; what we could do is set a default value if none is given. However, this is more complex than it seems. The good news is that everything should work fine with python 3.7.
The reason is the encoding that python assumes. You can try the following with different python versions in systems that do not set the locale vars (`LANG`, `LC_ALL`, etc). 

```python
python3 -c "import locale; print(locale.CODESET, locale.getpreferredencoding(locale.CODESET))"
```

The `CODESET` should be `14` but the preferred encoding changes from `ANSI_X3.4-1968` (in pre-py3.7) to `UTF-8` (py3.7+). This change allows the `Click` library to work without any need for change/configuration by the user.

References:
https://bugs.python.org/issue28180
https://www.python.org/dev/peps/pep-0538/
https://www.python.org/dev/peps/pep-0540/

**Comment by c00kiemon5ter** [comment]
This brings up another point. We have updated the base image to be a newer ubuntu image; and we have pin-pointed such specific ubuntu version (18.04 in this case). However, I do not care about that specific ubuntu version. What I care about is to have a modern, stable, base image.

It would be great if I could be following such a base image without the need to be updating the tag to keep up with the image being updated. Ubuntu, due to the business and support model it follows, doesn't give us this ability. Additionally, in practice, Ubuntu is not used for any servers that my team manages; what we use is Debian. Debian gives us the `stable` tag (and also `stable-slim`).

So, I think we should be using `debian:stable-slim` as the base image. Current stable debian (buster, aka Debian 10) uses python 3.7 as the python3 version. With this change we fix this and hopefully we won't have to be pin-pointing specific distribution versions in the future.

In this spirit, I would also like to experiment with way smaller base images like google's _distroless_ base images.

**Comment by c00kiemon5ter** [comment]
I have pushed those changes along with a more streamlined Dockerfile in terms of the packages that get installed. The latest image should be running as expected, but now it runs on Debian stable-slim version. The new image should be much smaller.
